---
# deploy default
- name: deploy coolstore in {{ project_default }}
  shell: "{{ openshift_cli }} process -f {{ deployments_template }} --param=APP_VERSION=latest --param=HOSTNAME_SUFFIX={{ project_default }}.{{ hostname_suffix }} -n {{ project_default }} | {{ openshift_cli }} create -f - -n {{ project_default }}"
  ignore_errors: true

- name: deploy netflix oss in {{ project_default }}
  shell: "{{ openshift_cli }} create -f {{ netflix_oss_template }} -n {{ project_default }}"
  ignore_errors: true

- name: prune deployments in {{ project_default }}
  shell: "{{ openshift_cli }} delete dc,svc,route,pvc,cm -l {{ prune_deployments_selector }} -n {{ project_default }}"
  ignore_errors: true
  when:
  - prune_deployments_selector is defined
  - prune_deployments_selector is not none
  - prune_deployments_selector|trim != ""

# remove persistent storage
- import_tasks: make_ephemeral.yml
  vars:
    project_name: "{{ project_default }}"
  when: ephemeral