---
# deploy test
- name: deploy inventory in test
  shell: "{{ openshift_cli }} process -f {{ inventory_template }} --param=GIT_URI=http://{{ gogs_hostname}}/{{ gogs_admin_user }}/coolstore-microservice.git --param=GIT_REF=master --param=MAVEN_MIRROR_URL={{ maven_mirror_url }} -n {{ project_test }} | {{ openshift_cli }} create -f - -n {{ project_test }}"
  ignore_errors: true

- name: check if inventory template is installed in dev
  shell: "{{ openshift_cli }} get template inventory -n {{ project_dev }}"
  register: inventory_template_deploy_result
  ignore_errors: true
  changed_when: false

- name: install inventory template
  shell: >
    curl -sL {{ inventory_template }} | tr -d '\n' | tr -s '[:space:]' \
      | sed "s|\"MAVEN_MIRROR_URL\", \"value\": \"\"|\"MAVEN_MIRROR_URL\", \"value\": \"{{ maven_mirror_url }}\"|g" \
      | sed "s|\"https://github.com/jbossdemocentral/coolstore-microservice\"|\"http://{{ gogs_hostname }}/{{ gogs_user }}/coolstore-microservice.git\"|g" \
      | {{ openshift_cli }} create -f - -n {{ project_dev }}
  when: inventory_template_deploy_result|failed

# remove persistent storage
- import_tasks: make_ephemeral.yml
  vars:
    project_name: "{{ project_test }}"
  when: ephemeral

