---
# Promote CoolStore Images
- name: list image streams
  shell: "{{ openshift_cli }} get is -o json -n {{ from_project }}"
  register: is_list
  changed_when: false

- name: tag images in {{ project_prod }}
  shell: "{{ openshift_cli }} tag {{ from_project }}/{{ item.metadata.name }}:latest {{ project_prod }}/{{ item.metadata.name }}:prod"
  with_items: "{{ is_list.stdout|default('[]')|from_json|json_query('items') }}"
  when:
    - item|json_query("status.tags[?tag=='latest']") is not none
    - item|json_query("status.tags[?tag=='latest']")|trim() != '[]'

- name: tag images in {{ project_stage }}
  shell: "{{ openshift_cli }} tag {{ from_project }}/{{ item.metadata.name }}:latest {{ project_stage }}/{{ item.metadata.name }}:test"
  with_items: "{{ is_list.stdout|default('[]')|from_json|json_query('items') }}"
  when:
    - not disable_stage_project
    - item|json_query("status.tags[?tag=='latest']") is not none
    - item|json_query("status.tags[?tag=='latest']")|trim() != '[]'

- name: tag inventory blue/green images in {{ project_prod }}
  shell: "{{ openshift_cli }} tag {{ from_project }}/{{ bluegreen_image }}:latest {{ project_prod }}/{{ bluegreen_image }}:prod-{{ item }}"
  with_items: [ "green", "blue"]
  when:
    - bluegreen_image is defined
    - bluegreen_image is not none
    - bluegreen_image|trim() != ""